services:
  bot:
    build: .
    depends_on:
      - redis
    env_file:
      - bot_config.env

  redis:
      image: "redis:7"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - redis_data:/data

volumes:
  redis_data:
    external: false