services:
  bot:
    build: .
    depends_on:
      - redis
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_GUILD_ID
      - REDIS_URL
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

  redis:
      image: "redis:7"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - redis_data:/data
      expose:
        - "6379"
      ports:
        - "6379:6379"

volumes:
  redis_data:
    external: false